# Generated by Django 2.2.2 on 2019-06-27 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of your printer', max_length=50)),
                ('owner', models.CharField(help_text='Name of the owner', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('location', models.CharField(help_text='Where is your printer located? Street, building, floor, Shop Number', max_length=500)),
                ('opening_hours', models.CharField(default='07.00 a.m.', help_text='The time your shop opens eg 8.00 a.m.', max_length=10)),
                ('closing_hours', models.CharField(default='17.00 hrs', help_text='The time your shop closes eg 5.00 p.m.', max_length=10)),
                ('delivery', models.CharField(default='YES', help_text='Do you offer delivery services(Yes/No)', max_length=3)),
                ('phone', models.IntegerField(help_text='Your working phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
