# Generated by Django 2.2.2 on 2019-06-27 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('pages', models.IntegerField(help_text='Number of pages in the document')),
                ('copies', models.IntegerField(default=1, help_text='Number of copies to be printed. e.g 2')),
                ('printer', models.CharField(help_text='Where do you want the copy to be printed', max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.CharField(default='admin', max_length=400)),
            ],
        ),
    ]
