# Generated by Django 2.2.2 on 2019-06-27 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printitem',
            name='customer',
        ),
        migrations.AddField(
            model_name='printitem',
            name='user',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='printitem',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
