# Generated by Django 2.2.3 on 2019-07-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_auto_20190627_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printitem',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
